repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        name: RUN black

-    repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.7.3
     hooks:
        - id: ruff
          args: [ --fix ]
          name: RUN ruff
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: RUN isort